### ISSUE TITLE
Issue when importing genomic data with varying nSite per chromosomes.

### ISSUE THREAD

**Issue by DrMulusewFikere** [HighlanderLab/SIMplyBee#582] opened 2024-08-23 13:20 UTC
I recently attempted to import genomic data to test SIMplyBee pipeline and encountered some issues. To investigate further, I wrote a reproducible R script (attached). AlphasimR >  SIMplyBee R package has difficulties importing empirical data when the number of loci per chromosome is unequal.
[ImportingDataSIMplyBee.md](https://github.com/user-attachments/files/16729197/ImportingDataSIMplyBee.md)

**Comment by gregorgorjanc** [comment] 2024-08-23 14:28
@DrMulusewFikere thanks for the report!

For completeness, here is another examples of importing external data https://github.com/HighlanderLab/jbancic_alphasimr_plants/blob/main/04_Features/importExternalHaplo.R

Let's see. I have taken your script above and ran it to get this:

```
> ###################################
> # 1. Require library
> ###################################
> library(AlphaSimR)
Loading required package: R6
> library(SIMplyBee)

Attaching package: ‘SIMplyBee’

The following object is masked from ‘package:base’:

    split

> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:SIMplyBee’:

    collapse, combine

The following object is masked from ‘package:AlphaSimR’:

    mutate

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

>       testGeno <- matrix(0:2, nrow = 100, ncol = 3030)  
>       colnames(testGeno) <- paste("1",sep = '_', seq(ncol(testGeno)))
>       ####################
>       # 2.2. Create a psudo map data
>       ####################
>       set.seed(1)
>       markerName <- colnames(testGeno)
>       position <- round(runif(n=ncol(testGeno), min=0.2, max=50), digits = 3)
>       chromosome <- sort(sample(x = c(1,2,3,4,5), size  = ncol(testGeno), replace = TRUE))
>       testMap <- as.data.frame(cbind(markerName,chromosome,position))
>       testMap$markerName <- as.character(testMap$markerName)
>       testMap$chromosome <- as.character(testMap$chromosome)
>       testMap$position <- as.numeric(testMap$position)
>       ####################
>       # 2.3. Check input data and structure
>       ####################
>       all(colnames(testGeno) %in% testMap$markerName) # has to be TRUE
[1] TRUE
>       range(testGeno) # has to be a range between 0 to 2 i.e., 0,1,2
[1] 0 2
>       testGeno <- as.matrix(testGeno)
>       testFounderGenome = importInbredGeno(geno=testGeno,
+                                        genMap=testMap,
+                                        ped=NULL)
>       ####################
>       # 3.1. Check the imported data
>       ####################  
>       testFounderGenome@nInd
[1] 100
>       testFounderGenome@nLoci
[1] 588 601 601 619 621
>       testFounderGenome@nChr
[1] 5
>       class(testFounderGenome) # has to be MapPop
[1] "MapPop"
attr(,"package")
[1] "AlphaSimR"
>       isMapPop(testFounderGenome) # has to be TRUE
[1] TRUE
> ###############################
> # 4. Initialise SP
> ###############################
> SP <- SimParamBee$new(testFounderGenome)
> SP$setTrackRec(TRUE)
> SP$setTrackPed(isTrackPed = TRUE)
>       ####################
>       # 4.1. Create base pop or virgin queen
>       ####################   
>       basePop <- createCastePop(testFounderGenome, caste = "virginQueens")
Error in mapLoci(markers, genMap) : 
  all(markers %in% genMapMarkerNames) is not TRUE
> traceback()
6: stop(simpleError(msg, call = if (p <- sys.parent(1L)) sys.call(p)))
5: stopifnot(all(markers %in% genMapMarkerNames))
4: mapLoci(markers, genMap)
3: pullMarkerHaplo(pop, markers = paste(simParamBee$csdChr, csdSites, 
       sep = "_"), simParam = simParamBee)
2: editCsdLocus(ret, alleles = csdAlleles, simParamBee = simParamBee)
1: createCastePop(testFounderGenome, caste = "virginQueens")
```

So, the error comes from `editCsdLocus()` that calls `mapLoci()`, which is in AlphaSimR, so this suggests an AlphaSimR (not SIMplyBee?) issue.

@janaobsteter could you check what is happening here (are you doing anything specific in `editCsdLocus()` that wrongly calls `mapLoci()`) before we look into AlphaSimR?

**Comment by janaobsteter** [comment] 2024-08-26 08:20
@DrMulusewFikere , I had a look at the problem is not on our or AlphaSimR's side. When you construct the genetic map, all the markers in there are market to be on the first chromosome (1_positions), so when the `editCsd` function is trying to pull out markers on chromosome 3, it doesn't work. If I set the csd locus to be on chromosome 1, then everything works fine. So you need to correct your genetic map.

**Comment by gregorgorjanc** [comment] 2024-08-26 12:59
@janaobsteter thanks for looking at this.

@DrMulusewFikere please correct your script and report back so we can close this issue.

**Comment by DrMulusewFikere** [comment] 2024-08-26 22:35
@janaobsteter Thank you for your response. If I understood correctly, I believe I've tried the map format you mentioned. I've modified the code accordingly for you to review (map option commented). The map file has three columns: the markerName is written as chr_pos, the chromosome as 1-16, and the last column the position. If we set the "chromosome" column to a single value, such as all "1" instead of 1-16, it works. 
[ImportingDataSIMplyBee_2.md](https://github.com/user-attachments/files/16754429/ImportingDataSIMplyBee_2.md)

**Comment by janaobsteter** [comment] 2024-08-30 08:28
@DrMulusewFikere I had a look at this code again and the problem is still in the genMap you provide. You sample the position randomly by `position <- round(runif(n=ncol(testGeno), min=10, max=100), digits = 0)` which means it's not monotonically increasing nor has enough loci for the csd and looks super random:
![image](https://github.com/user-attachments/assets/aab6837c-05ed-4ca6-9444-2e3120cde330)

Create a proper genetic map with monotonously increasing position and enough loci and it will work.

**Comment by DrMulusewFikere** [comment] 2024-09-01 17:17
@janaobsteter I increased the number of loci from 3k to 10k and updated the mapFile, but the issue persists. I even encountered the same error when using real data (~300k SNPs) extrapolated from a VCF file. As shown in the attached code, I conducted tests like setting `baseQueens <- createVirginQueens(testFounderGenome, editCsd = FALSE`, which works. However, the issue reappears when running the `cross()` function. As you can see the line of my code, `AlphasimR` runs with no issue. Lastly, feel free to modify the code and surprise it's working.

**Comment by DrMulusewFikere** [comment] 2024-09-05 21:16
Issue resolved!
Initially, there were no problems or error messages when creating a founderGenome using imported data (AlphasimR).
To address this, I wrote a small R script to restructure the genMap file, allowing SIMplyBeeR functions like createVirginQueens, createColony, and cross to run without errors. Thank @janaobsteter  and @gregorgorjanc

**Comment by gregorgorjanc** [comment] 2024-09-05 21:42
Thanks for reporting back. Will now close this issue.

**Closed by gregorgorjanc** 2024-09-05 21:42 UTC
