### ISSUE TITLE
Problem with csd locus when choosing to simulate only two csd alleles

### ISSUE THREAD

**Issue by janaobsteter** [HighlanderLab/SIMplyBee#585] opened 2024-08-30 08:31 UTC
```
founderGenomes <- quickHaplo(nInd = 4, nChr = 1, segSites = 50)
SP <- SimParamBee$new(founderGenomes, nCsdAlleles = 2)
basePop <- createCastePop(founderGenomes, caste = "virginQueens")
```

This returns the error 

> Error in x[1, ] : incorrect number of dimensions

Because of the following check in the `editCsdLocus()`
```
  if (any(sapply(alleles, FUN = function(x) all(x[1, ] == x[2, ])))) {
    stop("You must provide two different alleles for each individual!")
  }
```

**Comment by gregorgorjanc** [comment] 2024-08-30 13:30
It looks like more that x has lost a dimension somewhere and is now not a matrix anymore? Sometimes this happens if we do x = x[,n] but n is 1 and then R is clever and converts matrix to a vector. I think it must be some to like that.

**Comment by gregorgorjanc** [comment] 2024-12-16 07:30
Duplicate of https://github.com/HighlanderLab/SIMplyBee/issues/591 - addressed in https://github.com/HighlanderLab/SIMplyBee/pull/592

**Closed by gregorgorjanc** 2024-12-16 07:30 UTC
Labels: bug
